# Generated by Django 3.2.9 on 2021-11-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=255)),
            ],
        ),
    ]
