# Generated by Django 3.2.9 on 2021-11-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="The food's name", max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text="The food's price", max_digits=5)),
            ],
        ),
    ]
