# Generated by Django 3.2.9 on 2021-11-17 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value_a', models.IntegerField()),
                ('value_b', models.IntegerField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.run')),
            ],
        ),
    ]
